### ISSUE TITLE
We are building Skim - inspired by arXiv Sanity with improvements :) 

### ISSUE THREAD

**Issue by prabhuomkar** [karpathy/arxiv-sanity-lite#1]
Hi @karpathy, thank you for introducing arXiv Sanity Lite!

Few of my peers and I are developing Skim https://skimhq.tech - Spotify for ML World - inspired by arXiv Sanity.

Currently it supports:
- Creating a list of papers as "Rack" (similar to Spotify playlist)
- See similar papers based on TF-IDF based features
- See popular conferences and their racks (arXiv papers bundled into racks based on their yearly proceedings) and conference statistics as well - giving you complete information about a conference :) 
- Search across all papers, racks, conferences and user base

We would like to discuss more and share an invite to you - so that we can collaborate on this and improve over time.
Please let us know - [prabhuomkar@pm.me](mailto:prabhuomkar@pm.me)

**Comment by karpathy** [comment]
Hi Omkar, thank you for the reference, it looks cool!  (Though I can't actually tell because I don't have an invite code :)). Arxiv Sanity has always been a bit of a little humble side project for late at nights, but it's awesome to see that it has inspired so many more serious projects that can take the core feature set and scale it up properly, without all the jank. Wish you guys all the best!

**Comment by prabhuomkar** [comment]
Thank you so much for the reply! The team is really inspired by your work.

I have sent you an invite on [andrej.karpathy@gmail.com](andrej.karpathy@gmail.com)!
Request your feedback :)))

Will close this issue in some time 👍

**Comment by Anri-Lombard** [comment]
2 months later... :-)

**Comment by dreamflasher** [comment]
@prabhuomkar Was looking forward to seeing it, but apparently it's down now. Any chance of reviving it?

arxiv-sanity-lite lacks the main feature I was using arxiv-sanity-preserver for: Most retweeted as a relevance proxy: http://www.arxiv-sanity.com/toptwtr?timefilter=month

**Comment by prabhuomkar** [comment]
Unfortunately we couldn't get time to focus more on releasing a stable version.
But an open version (with most features) is running here: https://skim.vercel.app/
