### ISSUE TITLE
Impossible to unsubscribe if login is forgotten

### ISSUE THREAD

**Issue by Randl** [karpathy/arxiv-sanity-lite#4]
If I've added e-mail to my account and managed to forget the login than there is no way to unsubscribe from what I can tell. One simple solution is to add login to e-mail body.

**Comment by karpathy** [comment]
Quick fix here: https://github.com/karpathy/arxiv-sanity-lite/commit/28163bfcb7776abcba75133773a994b0000705a8 . Good idea ty! Closing.
